path_for_scan_reports = 'C:/Users/ravidm/PycharmProjects/sca_client/scans_json'
path_for_scan_full_csv_stats = r"C:/Users/ravidm/PycharmProjects/sca_client/csv/"
path_for_scan_full_csv_stats_license = r"C:/Users/ravidm/PycharmProjects/sca_client/csv_license/"
#folder_path = 'C:\Users\ravidm\Downloads\_Zipped\vulpy-master.zip'
urls = {
# 'idno/known',
# 'envoyproxy/envoy',
# 'hashicorp/hcl',
# 'chef/bento',
# 'googlecloudplatform/google-auth-library-python',
# 'googleapis/google-auth-library-python',
# 'googleapis/python-api-core',
# 'kubernetes/release',
# 'google/trillian',
# 'GoogleCloudPlatform/cloud-bigtable-client',
# 'googleapis/python-service-usage',
# 'rust-vmm/vmm-sys-util',
# 'googleapis/synthtool',
# 'forcedotcom/salesforcedx-templates',
# 'googleapis/python-appengine-logging',
# 'googleapis/python-monitoring-dashboards',
# 'googleapis/python-network-connectivity',
# 'googleapis/python-talent',
# 'forcedotcom/sf-fx-sdk-nodejs',
# 'googleapis/python-aiplatform',
# 'MvvmCross/MvvmCross',
# 'googleapis/go-genproto',
# 'googleapis/gax-go',
# 'standard/eslint-config-standard-with-typescript',
# 'googleapis/google-cloud-php',
# 'prisma/prisma',
# 'coreinfrastructure/best-practices-badge',
# 'arnog/mathlive',
# 'uber/baseweb',
# 'prisma/prisma2',
# 'xtuc/webassemblyjs',
# 'LLK/scratch-vm',
# 'antelopesystems/crud-framework',
# 'googleapis/releasetool',
# 'googleapis/java-bigtable-hbase',
# 'googleapis/testing-infra-docker',
# 'elastic/package-spec',
# 'JanusGraph/janusgraph',
# 'googleapis/doc-pipeline',
# 'googleapis/python-life-sciences',
# 'googleapis/python-texttospeech',
# 'googleapis/python-data-qna',
# 'googleapis/python-resource-manager',
# 'googleapis/python-documentai',
# 'googleapis/python-access-context-manager',
# 'googleapis/google-auth-library-python-oauthlib',
# 'googleapis/python-service-control',
# 'googleapis/python-source-context',
# 'googleapis/python-memcache',
# 'googleapis/python-dataflow-client',
# 'googleapis/python-securitycenter',
# 'googleapis/python-recommendations-ai',
# 'googleapis/python-trace',
# 'googleapis/python-bigquery-connection',
# 'googleapis/python-dialogflow-cx',
# 'googleapis/python-tpu',
# 'googleapis/python-org-policy',
# 'googleapis/python-iot',
# 'googleapis/python-security-private-ca',
# 'googleapis/python-kms',
# 'googleapis/python-asset',
# 'googleapis/python-policy-troubleshooter',
# 'googleapis/python-pubsublite',
# 'thoughtbot/administrate',
# 'googleapis/python-recaptcha-enterprise',
# 'googleapis/python-channel',
# 'googleapis/python-containeranalysis',
# 'googleapis/python-test-utils',
# 'googleapis/python-logging',
# 'googleapis/python-videointelligence',
# 'googleapis/python-redis',
# 'googleapis/python-bigquery-logging',
# 'cosmos/cosmos-sdk',
# 'googleapis/python-api-gateway',
# 'googleapis/python-managed-identities',
# 'googleapis/python-bigquery-storage',
# 'googleapis/python-shell',
# 'googleapis/python-pubsub',
# 'googleapis/python-grafeas',
# 'apollographql/apollo-client',
# 'googleapis/python-service-directory',
# 'googleapis/python-runtimeconfig',
# 'googleapis/python-service-management',
# 'googleapis/python-gke-hub',
# 'googleapis/python-tasks',
# 'googleapis/python-analytics-admin',
# 'googleapis/python-resource-settings',
# 'jenkinsci/docker',
# 'googleapis/python-phishingprotection',
# 'googleapis/python-datacatalog',
# 'googleapis/python-analytics-data',
# 'googleapis/python-access-approval',
# 'googleapis/python-functions',
# 'googleapis/python-network-security',
# 'googleapis/python-storage',
# 'googleapis/python-retail',
# 'googleapis/python-recommender',
# 'googleapis/python-notebooks',
# 'googleapis/python-vision',
# 'googleapis/python-datalabeling',
# 'googleapis/python-bigquery',
# 'googleapis/python-speech',
# 'googleapis/python-oslogin',
# 'googleapis/python-automl',
# 'googleapis/python-appengine-admin',
# 'googleapis/python-dialogflow',
# 'alphagov/whitehall',
# 'googleapis/python-dlp',
# 'googleapis/google-api-php-client-services',
# 'googleapis/python-webrisk',
# 'googleapis/python-error-reporting',
# 'googleapis/python-apigee-connect',
# 'googleapis/python-eventarc',
# 'googleapis/python-datastore',
# 'googleapis/python-gke-connect-gateway',
# 'googleapis/python-vpc-access',
# 'bitcoin/bitcoin',
# 'googleapis/python-media-translation',
# 'googleapis/google-resumable-media-python',
# 'googleapis/python-billingbudgets',
# 'googleapis/python-essential-contacts',
# 'senteca/sdk',
# 'googleapis/python-dataproc',
# 'googleapis/python-iam',
# 'googleapis/python-language',
# 'cilium/cilium',
# 'googleapis/python-debugger-client',
# 'TryGhost/gatsby-starter-ghost',
# 'googleapis/python-compute',
# 'GoogleCloudPlatform/dotnet-docs-samples',
# 'googleapis/doc-templates',
# 'googleapis/python-os-config',
# 'googleapis/python-video-transcoder',
# 'googleapis/python-artifact-registry',
# 'googleapis/python-workflows',
# 'googleapis/python-ndb',
# 'googleapis/python-scheduler',
# 'googleapis/python-cloudbuild',
# 'googleapis/python-container',
# 'googleapis/python-dms',
# 'googleapis/python-private-catalog',
# 'helm/helm',
# 'googleapis/python-translate',
# 'googleapis/python-billing',
# 'codetriage/CodeTriage'}
# 'googleapis/python-dataproc-metastore',
# 'googleapis/python-dns',
# 'googleapis/python-game-servers',
# 'googleapis/python-secret-manager',
# 'googleapis/python-assured-workloads',
# 'googleapis/python-monitoring',
# 'googleapis/python-bigquery-reservation',
# 'googleapis/python-binary-authorization',
# 'googleapis/python-bigquery-datatransfer',
# 'googleapis/python-websecurityscanner',
# 'googleapis/python-cloud-core',
# 'googleapis/python-domains',
# 'Fody/Home',
# 'grafana/grafana-plugin-sdk-go',
# 'googleapis/python-iam-logging',
# 'apollographql/apollo-client-devtools',
# 'chef/ffi-libarchive',
# 'artsy/reaction',
# 'azu/safe-marked',
# 'xtuc/js-webassembly-interpreter',
# 'coinbase/salus',
# 'form8ion/eslint',
# 'phpservermon/phpservermon',
# 'googleapis/python-area120-tables',
# 'apollographql/apollo-server',
# 'GoogleCloudPlatform/ruby-docs-samples',
# 'artsy/detect-responsive-traits',
# 'artsy/fresnel',
# '18F/identity-idp',
# 'siddhi-io/siddhi',
# 'Financial-Times/x-dash',
# 'googleapis/conformance-tests',
# 'angular/ngcc-validation',
# 'opencontainers/runc',
# 'appium/python-client',
# 'GoogleCloudPlatform/php-docs-samples',
# 'elastic/cloud-on-k8s',
# 'kubernetes/deployment-manager',
# 'uber-web/baseui',
# 'kubeflow/pipelines',
# 'jenkinsci/pipeline-model-definition-plugin',
# 'TheThingsNetwork/lorawan-stack',
# 'nextcloud/server',
# 'go-gitea/gitea',
# 'kubernetes/helm',
# 'hyperledger/aries-framework-go',
# 'zalando-incubator/kubernetes-on-aws',
# 'oneapi-src/oneDAL',
# 'JoinColony/colonyNetwork',
# 'loopbackio/loopback-next',
# 'vue-styleguidist/vue-styleguidist',
# 'bitrise-io/go-utils',
# 'ks-no/fiks-virksomhetssertifikat',
# 'googleapis/python-audit-log',
# 'containers/image',
# 'visjs/vis-util',
# 'appium/appium-adb',
# 'stoplightio/elements',
# 'artsy/metaphysics',
# 'googlemaps/js-three',
# 'sylabs/scs-build-client',
# 'bgoonz/DS-ALGO-OFFICIAL',
# 'slimkit/plus',
# 'postmanlabs/newman',
# 'enkidevs/seapig',
# 'mulesoft/mule-http-service',
# 'GoogleCloudPlatform/nodejs-getting-started',
# 'sylabs/scs-key-client',
# 'banzaicloud/pipeline',
# 'scality/cloudserver',
# 'tunnckoCore/demo-minmorph',
# 'edgexfoundry/go-mod-bootstrap',
# 'apollographql/federation',
# 'dpc-sdp/ripple',
# 'hashicorp/packer-plugin-sdk',
# 'sarahdayan/dinero.js',
# 'edgexfoundry/go-mod-core-contracts',
# 'visjs/vis-network',
# 'qlik-oss/enigma-go',
# 'visjs/vis-data',
# 'hashgraph/hedera-sdk-go',
# 'chef/chef-vault',
# 'textlint/textlint',
# 'edgexfoundry/go-mod-messaging',
# 'dinerojs/dinero.js',
# 'edgexfoundry/go-mod-registry',
# 'chef/chef-zero',
# 'edgexfoundry/go-mod-secrets',
# 'felipefialho/piano',
# 'supermacro/neverthrow',
# 'containers/storage',
# 'ethereum/eth2.0-specs',
# 'dhis2/app-platform',
# 'aristanetworks/cloudvision-frontend-config',
# 'syncthing/syncthing',
# 'visjs/vis-timeline',
# 'jenkinsci/ec2-plugin',
# 'tinovyatkin/fun-dispatcher',
# 'doctrine/orm',
# 'owncloud-docker/server',
# 'googleapis/google-cloudevents-php',
# 'wenzhixin/bootstrap-table',
# 'ripple/ripple-keypairs',
# 'jessesquires/JSQCoreDataKit',
# 'coreos/openssh-keys',
# 'sylabs/json-resp',
# 'salesforce/design-system-react',
# 'cypress-io/code-coverage',
# 'plotly/dash-bio',
# 'edgexfoundry/device-sdk-go',
# 'actions/javascript-action',
# 'googleapis/docuploader',
# 'google/docsy-example',
# 'owncloud/core',
# 'zendeskgarden/react-containers',
# 'operator-framework/operator-sdk',
# 'artsy/force',
# 'ornikar/eslint-configs',
# 'googleapis/google-cloudevents-python',
# 'StackExchange/Stacks-Icons',
# 'maticzav/creato',
# 'giantswarm/helmclient',
# 'coreos/operator-sdk',
# 'DevExpress/devextreme-reactive',
# 'gravitational/teleport',
# 'mantisbt/mantisbt',
# 'zendeskgarden/css-components',
# 'containers/common',
# 'googleapis/python-api-common-protos',
# 'transferwise/icons',
# 'centreon/centreon',
# 'googleapis/gax-php',
# 'artsy/palette',
# 'appium/appium-base-driver',
# 'manniwatch/manniwatch',
# 'alphagov/router',
# 'strongloop/loopback-next',
# 'kumahq/kuma',
# 'wso2/siddhi',
# 'nestjs/graphql',
# 'Hermanya/use-interval',
# 'sulu/sulu',
# 'aws/serverless-application-model',
# 'mirumee/saleor',
# 'actions/labeler',
# 'wireapp/wire-desktop',
# 'cdimascio/express-openapi-validator',
# 'repman-io/repman',
# 'teamleadercrm/ui-icons',
# 'form8ion/readme'}
# 'qlik-oss/sn-action-button',
# 'worldturtlemedia/circleci-api',
# 'LearningLocker/xapi-validation',
# 'apple/swift-nio',
# 'MetaMask/controllers',
# 'ramsey/collection',
# 'gigobyte/purify',
# 'algolia/autocomplete.js',
# 'form8ion/core',
# 'dotnet/HttpRepl',
# 'falcosecurity/falco',
# 'netlify-templates/gatsby-starter-netlify-cms',
# 'signavio/react-stick',
# 'stipsan/scroll-into-view-if-needed',
# 'influxdata/influxdb',
# 'nestjs/mongoose',
# 'ericelliott/riteway',
# 'flarum/core',
# 'auth0/react-native-auth0',
# 'awslabs/amazon-eks-ami',
# '4Catalyzer/cli',
# 'nestjs/swagger',
# 'go-gorm/sqlserver',
# 'googleapis/google-auth-library-php',
# 'appcelerator/alloy-devkit',
# 'fabulator/rest-api-handler',
# 'saschagrunert/webapp.rs',
# 'oprogramador/array-starts-with',
# 'algolia/autocomplete',
# 'saschagrunert/git-journal',
# 'google/tcmalloc',
# 'dotnet/templating',
# 'nuxt-community/firebase-module',
# 'mruby/mruby',
# 'ossf/scorecard',
# 'amweiss/angular-diff-match-patch',
# 'levanto-financial/ember-lodash',
# 'felipefialho/kratos-boilerplate',
# 'digital-asset/daml',
# 'coinbase/rosetta-sdk-go',
# '5app/base5-ui',
# 'stackstorm/st2web',
# 'fabulator/gpx-builder',
# 'hashicorp/packer-plugin-amazon',
# 'ornikar/shared-configs',
# 'tendermint/tendermint',
# 'xwiki/xwiki-rendering',
# 'sylabs/scs-library-client',
# 'ndelvalle/v-click-outside',
# 'NoriSte/cypress-wait-until',
# 'apollographql/apollo',
# 'form8ion/husky',
# 'unhappychoice/cycle-pusher',
# 'algolia/react-instantsearch',
# 'nestjs/jwt',
# 'form8ion/lift-javascript',
# 'fomantic/Fomantic-UI',
# 'streamich/mdast-flat',
# 'stipsan/smooth-scroll-into-view-if-needed',
# 'VernierST/godirect-js',
# 'koddr/goodshare.js',
# 'fabulator/storage-keeper',
# 'RocketChat/Rocket.Chat',
# 'PHPMailer/PHPMailer',
# 'hwi/HWIOAuthBundle',
# 'SteeltoeOSS/Steeltoe',
# 'form8ion/javascript-core',
# 'spree/spree',
# 'aws/jsii',
# 'coreos/rpm-ostree',
# 'Homebrew/brew',
# 'travi/remark-preset-lint-travi',
# 'wmfs/smithereens',
# 'marshmallow-code/webargs',
# 'awslabs/jsii',
# 'hashicorp/packer-plugin-digitalocean',
# 'pixelastic/norska',
# 'wbkd/react-flow',
# 'mozilla/web-ext',
# 'github/explore',
# 'pyca/cryptography',
# 'coralproject/talk',
# 'SAP/luigi',
# 'AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet',
# 'wmfs/xml-flatten2csv',
# 'wmfs/sharepoint',
# 'junkurihara/jseu',
# 'wmfs/pg-info',
# 'facebookincubator/propfuzz',
# 'wmfs/json-schema-builder',
# 'lowdefy/lowdefy',
# 'young-steveo/bottlejs',
# 'streamich/memfs',
# 'form8ion/remark-lint-preset',
# 'imgix/drift',
# 'wmfs/relationize',
# 'wmfs/json-schema-to-cardscript',
# 'Automattic/jetpack',
# 'nuxt/nuxtjs.org',
# 'PrivateBin/PrivateBin',
# 'wmfs/tymly-data-types',
# 'Trustroots/trustroots',
# 'hashicorp/terraform-ls',
# 'bitrise-io/go-xcode',
# 'actions/stale',
# 'jonhue/notifications-rails',
# 'webex/webex-js-sdk',
# 'wmfs/rbac',
# 'wmfs/asl-choice-processor',
# 'hashicorp/terraform-json',
# 'webcomponents/custom-elements-everywhere',
# 'wmfs/tymly-pg-plugin',
# 'streamich/linkfs',
# 'alxshelepenok/gatsby-starter-lumen',
# 'wmfs/j2119',
# 'fwoelffel/nest-bull',
# 'tinymce/tinymce-react',
# 'hypothesis/browser-extension',
# 'fergiemcdowall/ngraminator',
# 'hashicorp/packer-plugin-docker',
# 'kichiyaki/gopgutil',
# 'travi/javascript-scaffolder',
# 'imgix/luminous',
# 'wmfs/tymly-statelint',
# 'imgix/imgix-core-js',
# 'wmfs/statelint',
# 'mendersoftware/go-lib-micro',
# 'typescript-eslint/tslint-to-eslint-config',
# 'joshuaslate/type-cacheable',
# 'wmfs/pg-diff-sync',
# 'webex/spark-js-sdk',
# 'schxslt/schxslt',
# 'imgix/react-imgix',
# 'DevExpress/devextreme-cli',
# 'imgix/js-core',
# 'apache/maven-apache-parent',
# 'wmfs/cardscript-schema',
# 'Kong/kubernetes-ingress-controller',
# 'tinymce/tinymce',
# 'ayonious/console-table-printer',
# 'craftcms/feed-me',
# 'imgix/imgix.js',
# 'googleapis/repo-automation-bots',
# 'wmfs/tymly-etl-plugin',
# 'nodejs/docker-node',
# 'calvinlough/ember-tag-input',
# 'callstack/react-native-testing-library',
# 'onikienko/7zip-min',
# 'tailscale/tailscale',
# 'wmfs/cardscript-examples',
# 'yowainwright/developer-ci-benefits-demo',
# 'wmfs/xml2csv',
# 'IBM/cloudant-java-sdk',
# 'asecurityteam/component-httpclient',
# 'jbolda/gatsby-source-airtable',
# 'nestjs/schematics',
# 'hashicorp/packer-plugin-converge',
# 'taskcluster/fast-azure-storage',
# 'hashicorp/packer-plugin-azure',
# 'algolia/docsearch'}
# '84codes/go-api',
# 'cosmos/ibc-go',
# 'influxdata/influxdb_iox',
# 'isaachinman/next-i18next',
# 'apollographql/apollo-ios',
# 'googleapis/nodejs-monitoring',
# 'googleapis/gax-dotnet',
# 'corona-warn-app/cwa-server',
# 'kubeapps/kubeapps',
# 'citusdata/pg_auto_failover',
# 'sigstore/cosign',
# 'googleapis/google-cloudevents-ruby',
# 'stanford-oval/string-interp',
# 'googleapis/python-bigquery-sqlalchemy',
# 'hashicorp/packer-plugin-googlecompute',
# 'koddr/vue-goodshare',
# 'edx/paragon',
# 'hashicorp/packer-plugin-ansible',
# 'cypress-io/cypress-istanbul',
# 'kofrasa/mingo',
# 'segmentio/analytics-java',
# 'ks-no/kryptering',
# 'hashicorp/packer-plugin-cloudstack',
# 'iamturns/eslint-config-airbnb-typescript',
# 'crowi/crowi',
# 'nationalarchives/tdr-generated-graphql',
# 'salsita/dripping-bucket',
# 'oclif/plugin-update',
# 'pixielabs/cavy',
# 'yowainwright/generate-clean-number',
# 'jessestuart/docker-hub-graphql-api',
# 'OpenZeppelin/openzeppelin-contracts',
# 'rackai/domql',
# 'netlify/js-client',
# 'OpenZeppelin/zeppelin-solidity',
# 'aserto-dev/clui',
# 'GoogleCloudPlatform/google-cloud-node',
# 'google/cctz',
# 'google/WebFundamentals',
# 'quiltdata/quilt',
# 'googleapis/google-auth-library-python-httplib2',
# 'qlik-oss/sn-table',
# 'resin-io-modules/resin-components',
# 'google/go-attestation',
# 'jonycheung/deadsimple-less-watch-compiler',
# 'terascope/teraslice',
# 'nestjs/nest-cli',
# 'tootsuite/mastodon',
# 'matomo-org/matomo',
# 'LLK/scratch-gui',
# 'adobe/aem-project-archetype',
# 'ocetnik/react-native-background-timer',
# 'square/keywhiz',
# 'mscharley/generic-type-guard',
# 'Financial-Times/n-health',
# 'stanford-oval/node-smtlib',
# 'herkulano/d3-hist2d',
# 'qlik-oss/sn-mekko-chart',
# 'payid-org/utils',
# 'foray1010/didyoumean2',
# 'tauri-apps/wry',
# 'infinitered/reactotron-core-client',
# 'heroku/heroku-buildpack-php',
# 'auth0/nextjs-auth0',
# 'fomantic/fomantic-ui',
# 'bahmutov/cypress-skip-and-only-ui',
# 'MrZillaGold/discord.js-pages',
# 'reactstrap/reactstrap',
# 'pixelastic/gilmore',
# 'hden/socketio-wildcard',
# 'Nordstrom/chef-vault',
# 'stanford-oval/thingtalk-units',
# 'googleapis/nodejs-gke-connect-gateway',
# 'googleapis/disco-to-proto3-converter',
# 'angular/angular-cli',
# 'abaldeweg/components',
# 'wmfs/pg-delta-file',
# 'electron/electron-quick-start-typescript',
# 'ain/smartbanner.js',
# 'teamleadercrm/ui-illustrations',
# 'nestjs/passport',
# 'forcedotcom/source-deploy-retrieve',
# 'electron/electron-rebuild',
# 'enarx/enarx',
# 'dhis2/app-runtime',
# 'foray1010/image-process-loader',
# 'googleapis/java-resource-settings',
# 'nestjs/schedule',
# 'cdaringe/semantic-ui-react-input-file',
# 'RobBrazier/svelte-awesome',
# 'DanSnow/vue-recaptcha',
# 'sqrthree/eslint-config-base',
# 'blockchain-certificates/explorer-lookup',
# 'MetaMask/eth-sig-util',
# 'hashicorp/terraform-exec',
# 'backstage/backstage',
# 'alphagov/digitalmarketplace-govuk-frontend',
# 'bbyars/mountebank',
# 'jkeiser/chef-zero',
# 'belaban/JGroups',
# 'paazmaya/yaml-validator',
# 'ipfs/ipfs-cluster',
# 'mscharley/inversify-token',
# 'stanford-oval/ThingTalk',
# 'fergiemcdowall/stopword',
# 'mike-north/jsonapi-typescript',
# 'LeSuisse/vue-dompurify-html',
# 'freshbooks/ember-responsive',
# 'streamich/unionfs',
# 'react-native-community/hooks',
# 'ndxbn/create-akashic',
# 'nestjs/axios',
# 'KazanExpress/vue-simple-suggest',
# 'nestjs/mapped-types',
# 'mallowigi/mtslack',
# 'auth0/auth0-spa-js',
# 'barajs/bara-react',
# 'apache/hbase',
# 'pubpub/pubpub',
# 'davidtheclark/tabbable',
# 'apollographql/apollo-codegen',
# 'growingio/gio-design-utils',
# 'googleapis/google-cloud-datastore',
# 'mike-north/micro-observable',
# 'nestjs/cqrs',
# 'apache-superset/superset-ui',
# 'bahrus/xtal-link-preview',
# 'moznion/proxy-protocol-js',
# 'inspec/train',
# 'cozy/cozy-ui',
# 'wmfs/statebox',
# 'mike-north/ember-lodash',
# 'finos/legend-studio',
# 'Financial-Times/next-logger',
# 'AxeriDev/Ember',
# 'LLK/scratch-blocks',
# 'nitram509/macaroons.js',
# 'unicar9/jizhi',
# 'bitrise-io/go-steputils',
# 'bpmn-io/bpmn-js-disable-collapsed-subprocess',
# 'mrog/LittleProxy',
# 'actionhero/ah-sequelize-plugin',
# 'mike-north/json-typescript',
# 'chriswells0/node-sitka',
# 'googleapis/go-type-adapters',
# 'best-shot/babel-preset-evergreen',
# 'streamlit/streamlit',
# 'streamich/libsys',
# 'Financial-Times/n-myft-ui',
# 'pkgw/slurm-rs',
# 'financial-times/next-logger',
# 'asecurityteam/transportd',
# 'googleapis/java-private-catalog',
# 'GoogleCloudPlatform/google-cloud-datastore',
# 'wmfs/tymly-core',
# 'stanford-oval/thingtalk',
# 'fishtown-analytics/dbt',
# 'cdaringe/webjerk',
# 'unboundedsystems/deploy-react-app',
# 'forcedotcom/salesforcedx-apex',
# 'koajs/html-minifier',
# 'wmfs/pg-telepods',
# 'nestjs/config',
# 'oprogramador/deep-equal-in-any-order',
# 'paritytech/polkadot',
# 'opscode/artifactory-client',
# 'nakatanakatana/eslint-config',
# 'wmfs/supercopy',
# 'pagarme/pagarme-js',
# 'jquense/yup',
# 'PicnicSupermarket/oss-parent',
# 'mike-north/mdast-builder',
# 'kkomelin/isomorphic-dompurify',
# 'h5bp/Front-end-Developer-Interview-Questions',
# 'standard/standard',
# 'wmfs/json-to-vuelidate'}
# 'dhis2/ui',
# 'AurityLab/domain-matcher',
# 'hashicorp/packer-plugin-hyperone',
# 'apollostack/apollo-client',
# 'nestjs/event-emitter',
# 'nestjs/typeorm',
# 'streamich/fs-monkey',
# 'dotnet/project-system',
# 'auth0/auth0.js',
# 'killtheliterate/diesocketdie',
# 'CourtHive/MatchUpFormatCode',
# 'mapbox/mapbox-gl-js',
# 'dhis2/prop-types',
# 'STORIS/react-scrollbar-size',
# 'kagawagao/gbt2260',
# 'hashicorp/packer-plugin-vsphere',
# 'mozilla/sign-addon',
# 'mike-works/pwa-fundamentals',
# 'jazzband/django-simple-history',
# 'iCrawl/eslint-config-aqua',
# 'appium/WebDriverAgent',
# 'shawnmcknight/react-scrollbar-size',
# 'hashicorp/packer-plugin-qemu',
# 'dialogflow/dialogflow-nodejs-client-v2',
# 'kcfe/dobux',
# 'truenorth/ember-lodash',
# 'googleapis/google-api-go-client',
# 'GoogleCloudPlatform/getting-started-python',
# 'focus-trap/tabbable',
# 'patternfly/patternfly-react',
# 'apollographql/apollo-tooling',
# 'wmfs/hl-pg-client',
# 'wmfs/pg-model',
# 'electron/electron-quick-start',
# 'cvgellhorn/webpack-boilerplate',
# 'validator/validator',
# 'nestjs/ng-universal',
# 'pkgw/stund',
# 'alexkcollier/dice-roller-dnd',
# 'wbkd/webpack-starter',
# 'awslabs/aws-api-gateway-developer-portal',
# 'JustinBeckwith/gaxios',
# 'bahrus/carbon-copy',
# 'mike-north/object-predicate',
# 'open-wa/wa-decrypt-nodejs',
# 'googleapis/nodejs-error-reporting',
# 'ohbarye/react-use-kana',
# 'Pelican-Elegant/elegant',
# 'calamares/calamares',
# 'mumble-voip/mumble',
# 'bpmn-io/bpmn-js-executable-fix',
# 'oprogramador/sort-any',
# 'egoist/vue-content-loader',
# 'ajmnz/custom-cursor-react',
# 'jessestuart/docker-hub-utils',
# 'edx/edx-bootstrap',
# 'express-promise-router/express-promise-router',
# 'coreos/ignition',
# 'LN-Zap/zap-desktop',
# 'keptn/keptn',
# 'transferwise/neptune-web',
# 'dailymotion/vast-client-js',
# 'shadow/shadow',
# 'hashicorp/packer-plugin-puppet',
# 'dmlemeshko/ms-edge-driver',
# 'Royal-Navy/design-system',
# 'elabftw/elabftw',
# 'jessesquires/PresenterKit',
# 'cozy/cozy-libs',
# 'streamich/freestyler',
# 'tunnckoCore/koa-better-serve',
# 'auth0/docs',
# 'junkurihara/cascade',
# 'dockwa/simple-react-validator',
# 'StellarCN/py-stellar-base',
# 'sonirico/datetoken.js',
# 'cozy/cozy-konnector-libs',
# 'SAP/ui5-webcomponents-react',
# 'sachinraja/create-si',
# 'form8ion/dependabot-scaffolder',
# 'googleapis/google-cloudevents',
# 'googleapis/google-cloud-cpp',
# 'softwareventures/array',
# 'nuxt-community/jimp-compact',
# 'travi/github-scaffolder',
# 'salesforce/lwc',
# 'bloomberg/record-tuple-polyfill',
# '18F/18f.gsa.gov',
# 'navikt/fnrvalidator',
# 'realpython/materials',
# 'openfoodfacts/openfoodfacts-server',
# 'processmaker/vue-form-elements',
# 'actionhero/ah-next-plugin',
# 'edgexfoundry/edgex-go',
# 'nestcn/docs.nestjs.cn',
# 'module-federation/module-federation-examples',
# 'openshift/installer',
# 'form8ion/github-actions-node-ci',
# 'cotejp/webmidi',
# 'GeopJr/SveltePress',
# 'microsoft/clarity',
# 'marshmallow-code/marshmallow',
# 'filecoin-project/slate',
# 'dependabot/dependabot-core',
# 'prometheus-community/windows_exporter',
# 'Sylius/Sylius',
# 'filecoin-project/specs-actors',
# 'AsynkronIT/protoactor-go',
# 'bbc/psammead',
# 'open-policy-agent/gatekeeper',
# 'davidtheclark/focus-trap-react',
# 'FYN-Software/component',
# 'microsoft/CsWin32',
# 'banzaicloud/banzai-charts',
# 'kantord/LibreLingo',
# 'jgroups-extras/native-s3-ping',
# 'SAP/fundamental-vue',
# 'rust-lang/cargo',
# 'lykmapipo/logger',
# 'googleapis/java-pubsublite-spark',
# 'elninotech/uppload',
# 'googleapis/nodejs-logging-bunyan',
# 'apollostack/graphql-server',
# 'saucelabs/ci-sauce',
# 'posva/vuex-mock-store',
# 'barc/express-hbs',
# 'softwareventures/dictionary',
# 'guzzle/psr7',
# 'alphagov/verify-hub',
# 'laminas/laminas-code',
# 'forcedotcom/lightning-language-server',
# 'Financial-Times/n-raven',
# 'qiwi/uniconfig',
# 'travi/node-app-engine-standard-scaffolder',
# 'travi/netlify-scaffolder',
# 'jedisct1/rust-dnsclient',
# 'hashicorp/packer-plugin-hyperv',
# 'asynkronit/protoactor-go',
# 'knative/community',
# 'hashicorp/packer-plugin-hcloud',
# 'Sunoo/philips-air',
# 'wireapp/wire-server',
# 'travi/octokit-auth-netrc',
# 'DeFiCh/jellyfish',
# 'qiwi/mware',
# 'open-telemetry/community',
# 'booleans-oss/DiscGit',
# 'shelfio/jest-mongodb',
# 'ciscospark/spark-js-sdk',
# 'apollostack/apollo-server',
# 'TheOdinProject/theodinproject',
# 'z-song/laravel-admin',
# 'tanmen/disassemble-package',
# 'softwareventures/date',
# 'open-telemetry/opentelemetry-js-api',
# 'microsoft/vs-mef',
# 'enkodellc/blazorboilerplate',
# 'qlik-oss/sn-scatter-plot',
# 'offchainlabs/arbitrum',
# 'understrap/understrap',
# 'googleapis/protoc-java-resource-names-plugin',
# 'lykmapipo/common',
# 'owncloud/ocis',
# 'terrestris/geostyler-wfs-parser',
# 'hyperledger/fabric-chaincode-node',
# 'taozhi8833998/node-sql-parser',
# 'ampproject/amphtml',
# 'hashicorp/packer-plugin-lxc',
# 'pac4j/jax-rs-pac4j',
# 'SAP/inquirer-gui',
# 'pac4j/dropwizard-pac4j',
# 'open-telemetry/opentelemetry-go-build-tools',
# 'atomist-skills/skill-logging',
# 'zkochan/packages',
# 'honeycombio/beeline-go',
# 'samselikoff/ember-cli-mirage',
# 'UltimaPhoenix/luceneappengine',
# 'nestjs/bull',
# 'ZsgsDesign/NOJ',
# 'unhappychoice/cycle-cropper',
# 'hashicorp/packer-plugin-oneandone',
# 'form8ion/cypress-scaffolder',
# 'Tencent/rapidjson',
# 'yahoo/elide',
# 'miloyip/rapidjson',
# 'apollographql/subscriptions-transport-ws',
# 'adobe/react-spectrum',
# 'jenkinsci/docker-inbound-agent',
# 'coreos/fcct',
# 'mentos1386/nest-raven',
# 'honeycombio/libhoney-go',
# 'auth0/lock',
# 'abhinaba-ghosh/cypress-react-selector',
# 'gocardless/business',
# 'DirectXMan12/k8s-prometheus-adapter',
# 'banterability/dateline',
# 'MetaMask/eth-simple-keyring',
# 'pixelastic/firost',
# 'Miodec/monkeytype',
# 'pixelastic/golgoth',
# 'adaptlearning/adapt_framework'}
# 'cloudflare/quiche',
# 'tryghost/gatsby-plugin-advanced-sitemap',
# 'cloudflare/kv-asset-handler',
# 'integrations/terraform-provider-github',
# 'ks-no/fiks-io-asice-handler',
# 'auth0/node-auth0',
# 'TryGhost/Koenig',
# 'mauricedb/polly-js',
# 'freedomofpress/securedrop',
# 'dmandalidis/docker-client',
# 'hashicorp/packer-plugin-outscale',
# 'atlassian/react-beautiful-dnd',
# 'mrz1836/go-ses',
# 'odota/core',
# 'webdriverio/expect-webdriverio',
# 'qlik-oss/nebula.js',
# 'googleapis/nodejs-security-private-ca',
# 'Roave/BetterReflection',
# 'googleapis/nodejs-firestore',
# 'snapview/tungstenite-rs',
# 'Cweili/svelte-fa',
# 'googleapis/java-iamcredentials',
# 'smonn/directus-migrate',
# 'googleapis/release-please',
# 'googleapis/nodejs-service-usage',
# 'googleapis/java-notebooks',
# 'googleapis/nodejs-essential-contacts',
# 'googleapis/java-logging-logback',
# 'googleapis/java-iam',
# 'googleapis/nodejs-artifact-registry',
# 'containers/buildah',
# 'microsoft/calculator',
# 'googleapis/java-datalabeling',
# 'Microsoft/rushstack',
# 'googleapis/google-auth-library-java',
# 'googleapis/java-spanner',
# 'BadChoice/handesk',
# 'mozilla-services/socorro',
# 'trailheadapps/lwc-recipes',
# 'googleapis/java-area120-tables',
# 'googleapis/java-securitycenter-settings',
# 'storybooks/storybook',
# 'googleapis/nodejs-game-servers',
# 'zalando/opentracing-toolbox',
# 'googleapis/nodejs-policy-troubleshooter',
# 'googleapis/nodejs-language',
# 'googleapis/java-pubsublite',
# 'aws-amplify/docs',
# 'google/google-auth-library-nodejs',
# 'googleapis/nodejs-cloudbuild',
# 'googleapis/java-automl',
# 'Laravel-Lang/lang',
# 'googleapis/nodejs-dms',
# 'googleapis/nodejs-resource-manager',
# 'googleapis/java-bigtable',
# 'pixelastic/imoen',
# 'googleapis/java-conformance-tests',
# 'googleapis/java-websecurityscanner',
# 'hashicorp/packer-plugin-tencentcloud',
# 'google/go-github',
# 'Jasig/java-cas-client',
# 'googleapis/nodejs-service-control',
# 'googleapis/nodejs-bigquery-reservation',
# 'vorburger/ch.vorburger.exec',
# 'netlify/netlify-plugin-edge-handlers',
# 'hashicorp/packer-plugin-profitbricks'}
'dashingsoft/pyarmor',
'inrupt/lit-vocab-term-js',
'googleapis/sloth',
'google/google-api-nodejs-client',
'googleapis/java-vision',
'microsoft/nnfusion',
'googleapis/java-filestore',
'googleapis/nodejs-bigquery-connection',
'googleapis/java-dataproc',
'TryGhost/slimer',
'alphagov/govuk-prototype-kit',
'googleapis/java-workflow-executions',
'Hack23/sonar-cloudformation-plugin',
'googleapis/java-trace',
'netlify/framework-info',
'googleapis/nodejs-assured-workloads',
'googleapis/nodejs-datacatalog',
'kadirahq/react-storybook',
'googleapis/java-firestore',
'googleapis/java-dialogflow-cx',
'googleapis/nodejs-monitoring-dashboards',
'GoogleCloudPlatform/gcloud-python',
'dromara/sa-token',
'lxerxa/actionview',
'googleapis/java-billingbudgets',
'pixijs/pixi-spine',
'googleapis/java-dlp',
'tektoncd/chains',
'googleapis/nodejs-grafeas',
'googleapis/google-cloud-node',
'googleapis/java-pubsub',
'canonical-web-and-design/cookie-policy',
'vega/react-vega',
'relative-ci/bundle-stats',
'googleapis/java-core',
'travi/travis-scaffolder-javascript',
'googleapis/java-memcache',
'googleapis/nodejs-text-to-speech',
'googleapis/java-pubsublite-kafka',
'salesforcecli/plugin-telemetry',
'Hazmi35/eslint-config',
'googleapis/java-bigquerystorage',
'ergebnis/composer-normalize',
'googleapis/java-vpcaccess',
'JustFly1984/react-google-maps-api',
'llogiq/flamer',
'Hacker0x01/react-datepicker',
'googleapis/nodejs-datalabeling',
'kubernetes/api',
'googleapis/nodejs-dataproc-metastore',
'keycloak/keycloak-nodejs-admin-client',
'googleapis/java-analytics-data',
'lykmapipo/express-rest-actions',
'Financial-Times/n-mask-logger',
'streamich/md-mdast',
'tunnckocore/flatten-arguments',
'matzkoh/prettier-plugin-packagejson',
'googleapis/nodejs-gke-hub',
'googleapis/googleapis.github.io',
'googleapis/nodejs-media-translation',
'GoogleCloudPlatform/java-docs-samples',
'googleapis/java-storage',
'googleapis/nodejs-notebooks',
'stanford-oval/thingpedia-api',
'googleapis/java-analytics-admin',
'googleapis/java-tasks',
'google/google-p12-pem',
'phpmyadmin/phpmyadmin',
'mongodb/go-client-mongodb-atlas',
'googleapis/nodejs-workflows',
'googleapis/nodejs-domains',
'aws/aws-sdk-js-crypto-helpers',
'primefaces-extensions/core',
'hashicorp/terraform-plugin-go',
'googleapis/nodejs-bigquery',
'SAP/ui5-logger',
'googleapis/java-phishingprotection',
'googleapis/nodejs-billing',
'googleapis/nodejs-logging',
'googleapis/java-gke-connect-gateway',
'sourcegraph/sourcegraph',
'SAP/ui5-cli',
'adobe/helix-shared',
'cloudfoundry/guardian',
'googleapis/nodejs-dns',
'googleapis/java-shell',
'googleapis/java-dialogflow',
'angular/universal',
'stevespringett/cvss-calculator',
'googleapis/nodejs-containeranalysis',
'netlify/cli',
'pingcap/parser',
'googleapis/java-life-sciences',
'googleapis/proto3-json-serializer-nodejs',
'googleapis/google-p12-pem',
'zalando/tracer',
'googleapis/java-translate',
'googleapis/java-networkconnectivity',
'googleapis/google-api-java-client-services',
'googleapis/nodejs-data-qna',
'googleapis/java-managed-identities',
'googleapis/java-eventarc'}
